# Generated by Django 6.0 on 2026-05-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(default='monthly', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_patients', models.PositiveIntegerField(default=0)),
                ('total_doctors', models.PositiveIntegerField(default=0)),
                ('total_appointments', models.PositiveIntegerField(default=0)),
                ('revenue_for_period', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('new_patients', models.PositiveIntegerField(default=0)),
                ('appointments_status_breakdown', models.JSONField(blank=True, default=list)),
                ('top_services', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('period_type', 'start_date', 'end_date')},
            },
        ),
    ]
