# Generated by Django 6.0 on 2026-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
