# Generated by Django 6.0 on 2026-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_workschedule_lunch_end_workschedule_lunch_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors_images/'),
        ),
    ]
