# Generated by Django 6.0 on 2026-04-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='identification_number',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
