# Generated by Django 6.0 on 2026-05-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_receipt_pdf'),
        ('medical_records', '0004_alter_treatmentrecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='services',
        ),
        migrations.AddField(
            model_name='invoice',
            name='treatment_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='medical_records.treatmentrecord'),
        ),
    ]
