# Generated by Django 6.0 on 2026-04-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        ('medical_records', '0001_initial'),
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='users.patient'),
        ),
        migrations.AddField(
            model_name='tooth',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='services',
            field=models.ManyToManyField(related_name='treatment_records', to='services.service'),
        ),
        migrations.AlterUniqueTogether(
            name='tooth',
            unique_together={('medical_record', 'tooth_number')},
        ),
    ]
