# Generated by Django 6.0 on 2026-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='teeth',
            field=models.ManyToManyField(blank=True, related_name='treatments', to='medical_records.tooth'),
        ),
    ]
