# Generated by Django 6.0 on 2026-05-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_treatmentrecord_teeth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
