# Generated by Django 6.0 on 2026-05-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
        ('medical_records', '0004_alter_treatmentrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_record', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
